### ISSUE TITLE
There is a fragile test case that attempts to match error messages from PCRE library

### ISSUE THREAD

**Issue by qbtf** [redis/librdb#57]
When I was in [the process](https://github.com/qbtf/librdb/tree/macos-compat) of making this library compile under macOS, I noticed that a specific test case kept failing. It is [this case for CLI](https://github.com/redis/librdb/blob/main/test/test_rdb_cli.c#L108) covering queries containing invalid regex. It should emit an error, and my test program did emit one, but the case still failed.

Upon further investigation, it emitted error messages that does not contain the words defined in the harness. I consider this case fragile -- it should not assume that the PCRE library emit specific error massage, because it can vary across implementations and the library itself can change wording deliberately. I suggest that the test case matches `FilterKey: Error compiling regular expression` as it is defined in librdb itself.

**Comment by moticless** [comment]
Hi @qbtf, would you be able to assist with fixing this issue? It it is reproducible on your platform.
Thanks.

**Comment by moticless** [comment]
@qbtf , i.e., maybe you can assist by creating pull request :)

**Comment by moticless** [comment]
@qbtf, I will review your CI to see what it takes to support mac. Thanks.
